### ISSUE TITLE
Option to tweak duration or remove overlay

### ISSUE THREAD

**Issue by iamchristopher** [Haacked/encourage-atom#11]
I find this package amusing but the length of time taken up by the darkened overlay has been a little frustrating at times. Would it be possible to add an option to tweak how long it is shown or remove the darkened overlay to prevent blocking the editor?

**Comment by Haacked** [comment]
@iamchristopher sure! It shouldn't be too hard to add as an option. I think all it would take is adding a property to https://github.com/Haacked/encourage-atom/blob/master/lib/config-schema.json and then using that in the timeout.

Let me know if you'd want to take a cut at it.

**Comment by iamchristopher** [comment]
I'd love to, but unfortunately I have no experience with developing Atom packages.

**Comment by Haacked** [comment]
Ok, I submitted a PR to fix this. 

> remove the darkened overlay to prevent blocking the editor?

What overlay are you referring to? Right now, when it's showing, it doesn't block the editor. You can still type. Is there some behavior I'm not aware of that actually blocks you?

**Comment by iamchristopher** [comment]
Yes, typing still functions correctly but mouse interactions are blocked (because a darkened overlay is applied) for the entire application: selecting text, switching tabs, sidebar functions et cetera.

Currently running Encourage v0.2.2 with Atom v1.9.0-beta0 on OSX.

**Comment by Haacked** [comment]
Could you add a screenshot of what you see when the overlay is applied?
Ideally a before and during one?

>

**Comment by iamchristopher** [comment]
Here are the screenshots. I switched to a light theme to make it easier to see. As you can see, while the overlay is applied, the entire editor is darkened.

Before:
<img width="1440" alt="screen shot 2016-08-01 at 5 28 39 pm" src="https://cloud.githubusercontent.com/assets/5909516/17309549/74744dd6-580d-11e6-8c2d-31cf33db1113.png">

During:
<img width="1440" alt="screen shot 2016-08-01 at 5 28 46 pm" src="https://cloud.githubusercontent.com/assets/5909516/17309550/74768074-580d-11e6-8634-031893969143.png">

**Comment by Haacked** [comment]
Whoah! Ok, thanks for the screenshots.

**Comment by iamchristopher** [comment]
You're welcome. Hope they help!

**Comment by simurai** [comment]
The "dark background" probably comes from the One dark/light UI theme. It's meant to direct the attention more onto the modal, but I guess in this case it feels too strong. It could be removed with:

```less
// Remove dark background for the One themes
.theme-one-dark-ui,
.theme-one-light-ui {
  .encourage.modal:after {
    display: none;
  }
}
```

Or another option might be to use some kind of lightweight overlay that shows up next to the cursor? Similar to autocomplete or linter.

**Comment by Haacked** [comment]
Thanks @simurai. I'd hate to add hacks for every theme that might do this. Is there a better approach I should be using?

**Comment by simurai** [comment]
> I'd hate to add hacks for every theme that might do this.

Yeah, it feels a bit ugly. Same if the One theme would make an exception just for this package. I guess there isn't a clear definition how a `.modal` should look like and every theme might style it a bit different.

@iamchristopher If you wanna keep using the One themes, you could add the above hack to 
your own [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file instead.

**Comment by Haacked** [comment]
> @iamchristopher If you wanna keep using the One themes, you could add the above hack to 
> your own styles.less file instead.

I'll add the hack to Encourage Atom.

@simurai I was wondering if there was another way to prominently display a message I should be using. I didn't want to use the status bar because it's barely noticeable for this.

**Comment by haacked** [comment]
@iamchristopher I published a fix. Could you try it out?

**Comment by jorbascrumps** [comment]
@Haacked That worked! I feel like there must be a better way to get around it, but this makes usage more practical for now. Thank you!
