### ISSUE TITLE
Allow users to configure the set of encouragements

### ISSUE THREAD

**Issue by Haacked** [Haacked/encourage-atom#3]
I haven't even looked into the proper way to create a settings UI in Atom. But I'd like to make it easy for people to replace the default set.

**Comment by armstnp** [comment]
This is likely something you'd set on the settings pane for the plugin, if I'm not mistaken.  Could be you could use a config file, of sorts, much like how atom stores its larger configs or keymaps.  Time to start digging!

**Comment by armstnp** [comment]
https://atom.io/docs/api/v1.2.0/Config

Looks like you create a schema that tells it how to build out the settings form automatically, and then it'll send out events whenever the config has been updated so you can pull new values down.  So you'd probably want a schema that looks something like:

```
{
 'encouragementList': {
    'description': 'The list from which encouragements will be selected.',
    'type': 'array',
    'default': [
        ... Place your current list here ...
    ],
    'items': {
      'type': 'string'
    }
  }
}
```

I might try fiddling around and seeing if I can drop a PR for this, seems like a nice slice of functionality.

**Comment by Haacked** [comment]
Thanks! This issue was closed by the PR https://github.com/Haacked/encourage-atom/pull/8

In the future, if you have a commit that closes an issue, you can put `Fixes #ISSUENUMBER` in the message of the commit and when that commit is merged into the master branch, GitHub will  automatically close the issue. It's pretty cool. :smile:

**Comment by armstnp** [comment]
Ahh, neat! Thanks for the feedback. :+1:

**Comment by charlesmilette** [comment]
BTW, the issue is not closed.

**Comment by Haacked** [comment]
Ha! Thanks for the reminder.
