### ISSUE TITLE
Misaligned modal panel on OS X

### ISSUE THREAD

**Issue by lee-dohm** [Haacked/encourage-atom#5]
It may be only on OS X:

![screen_shot_2016-06-07_at_10_13_26_am](https://cloud.githubusercontent.com/assets/1038121/15867794/ae4fba08-2c99-11e6-8db5-c008457fc886.png)

**Comment by lee-dohm** [comment]
Reproduced using Atom v1.9.0-dev-732d571 on Mac OS X 10.11.5.

**Comment by simurai** [comment]
This looks like a theme related issue. The One themes could be fixed with #6, although that feels a bit like haacking.
